### PR TITLE
Fix button pressing race condition

### PR DESCRIPTION
**Pull request by Patater**
@AlessandroA
@meriac

### CODE REVIEW

**Comment by AlessandroA** [comment]
I've left comments in the single commits.

As a general comment, is it worth to add all of this code? We could in alternative just initialize `g_box_context` to `0xFFFFFFFF`:
* The initialization will happen at libC time.
* A hard fault will be triggered if the button is pressed before the challenge is initialized (invalid address for a read).

I'm concerned about adding code that might confuse people. I'd like this example to stay as clean and minimalist as possible. Since this is not actually a bug, but rather a false positive, I'd go for the most seamless solution.

Commit https://github.com/Patater/uvisor-helloworld/commit/a99a49b55f70e92feef1ae8f5746a58902e4c445 is different, as it fixes a bug. Maybe it should go in a different PR?

@meriac ?

**Comment by Patater** [comment]
- Fix style violations

**Comment by meriac** [comment]
@AlessandroA I believe the code is clearer now after the changes proposed by @Patater - before we munged initialization and comparison into one function - which resulted in the mentioned problem and less readability. Also an important FIXME is resolved - the comparison to the secret itself.

**Comment by meriac** [comment]
@Patater please rebase &resolve conflicts

**Comment by Patater** [comment]
This PR is paused until https://github.com/ARMmbed/uvisor/pull/182 is merged.

**Comment by Patater** [comment]
I have verified that without the added check for overlapping box context, one can pass in g_box_context and pass the challenge verification.

**Comment by Patater** [comment]
Rebased on latest code

**Comment by Patater** [comment]
- Fix typo in commit description.

**Pull request merged**
