### PR TITLE
Add NUCLEO_F401RE and NUCLEO_F091RC

### PR DESCRIPTION
**Pull request by bcostm**

### CODE REVIEW

**Comment by meriac** [comment]
I suggest to combine both cases into one - as the difference is only TIM5. What do you guys think @Patater @AlessandroA?

**Comment by meriac** [comment]
@bcostm @AlessandroA To ensure that we don't create the wrong impression on supported uVisor targets, we should ensure that uVisor support is added first for the NUCLEO targets before adding support to uvisor_helloworld.

**Comment by bcostm** [comment]
OK I agree. I am trying to add uvisor on the stm32f401re by myself. I have added "uvisor_present" in the target.json but now there is a compilation error with the vIRQ_SetVector and vIRQ_EnableIRQ. There is certainly many other things to add. Can you help ? Is there a documentation to explain how to implement uvisor ?  Thanks.

**Comment by AlessandroA** [comment]
Hello @bcostm , I'm sorry I hadn't seen this comment in my notifications. I created a PR here https://github.com/ARMmbed/target-st-nucleo-f401re-gcc/pull/7 to revert the setting of `YOTTA_CFG_UVISOR_PRESENT` to `1`, as some users have reported a broken build.

Please let me know if the porting guide needs any adjustment to clarify the role of the configuration setting; any other feedback regarding the porting process is very welcome as well :)

**Comment by bcostm** [comment]
Hi,
Thanks to have changed the uvisor_present back to 0. 
No problem for the porting guide, I will send you my remarks if I have some.

**Comment by meriac** [comment]
@bcostm I am closing this ticket till NUCLEO_F401RE and NUCLEO_F091RC have uVIsor support.

**Comment by bcostm** [comment]
Yes ok no problem.

**Pull request closed without merging**
