### PR TITLE
Fix documentation (blinking patterns)

### PR DESCRIPTION
**Pull request by AlessandroA**
- The behaviour of the blinking pattern was outdated
- Also fixed some minor issues (broken links, typos)

[Rendered](https://github.com/ARMmbed/uvisor-helloworld/blob/fix_led_docs/README.md)

### CODE REVIEW

**Comment by AlessandroA** [comment]
Fixes https://github.com/ARMmbed/uvisor-helloworld/issues/27
@meriac 
@niklas-arm

**Comment by niklas-arm** [comment]
What about pressing SW1/2 ? It goes into the hard-fault handler with different blinking patterns for either switches?

**Comment by niklas-arm** [comment]
How do I know this works for the STM32F429?

**Comment by AlessandroA** [comment]
On K64F SW3 is tied to NMI_Handler, which is a system handler. It triggers a `NOT_ALLOWED` error blinking pattern. SW2 instead, which is the one used in the example, triggers a custom handler `btn_onpress()` which does some evil and hence triggers a `PERMISSION_DENIED` error.

I added some clarification on that in the docs.

What about the STM32F429? Is it a different issue from the one solved here? @niklas-arm

**Comment by niklas-arm** [comment]
Pressing the blue User button on the F429 doesn't do anything, especially it doesn't start blinking the red LED.

**Comment by AlessandroA** [comment]
It might be related to https://github.com/ARMmbed/uvisor-helloworld/issues/20
I will test again today and update here. Merging this meanwhile as it clarifies the expected behavior

**Pull request merged**
