### PR TITLE
Setting the uart baud rate to 115200

### PR DESCRIPTION
**Pull request by AlessandroA**
Fixes https://github.com/ARMmbed/uvisor-helloworld/issues/42

@meriac 
@mlnx

### CODE REVIEW

**Comment by meriac** [comment]
Shouldn't we fix the baud rate of the target instead ?

**Comment by AlessandroA** [comment]
From what I understood 115200 is the default baud rate to be used *for examples* not universally for a given target. @bogdanm is this correct?

**Comment by bogdanm** [comment]
@AlessandroA, yes, that is indeed the case.

**Comment by meriac** [comment]
@bogdanm  I am merging this pull-request to solve the immediate problem. Please ensure that mbed-drivers allows override of the default baud rate via YT_CONFIG_CONSOLE_BAUD_RATE or similar. If not defined it can still fall back to 9600 - it's unacceptable that 9600 baud is hard-coded.

**Pull request merged**
